project:
  type: website

website:
  title: "Website name"
  back-to-top-navigation: true
  favicon: "images/logo/favicon.png"
  
  navbar:
    pinned: false # mettre à true pour avoir la barre de menu toujours affichée
    logo: "images/logo/Logo RF Cerema verticalBR.jpg"
    logo-alt: "CEREMA"
    left:
      - icon: house
        href: index.qmd
        text: Accueil  

      - icon: file-richtext
        text: Pages exemples
        menu:        
        - icon: file-earmark-image
          href: exemple_page_rapport.qmd
          text: Exemple mise en page  
        - icon: file-bar-graph
          href: exemple_page_data.qmd
          text: Exemple analyses de données
          
      - icon: bi-journals
        text: Annexes
        menu:
          - icon: journal-bookmark
            href: glossaire.qmd
            text: Glossaire
          - icon: book
            href: bibliographie.qmd
            text: Bibliographie
      - icon: people
        href: presentation_cerema.qmd
        text: Qui sommes-nous ?
        
  page-footer:
    #left: "Site créé avec [Quarto](https://quarto.org/)"
    #center: "[©CEREMA](https://www.cerema.fr/fr)"
    left: "[©CEREMA](https://www.cerema.fr/fr)"
    right: 
      - icon: linkedin
        href: https://fr.linkedin.com/company/cerema
      - icon: twitter-x 
        href: https://x.com/ceremacom
      - icon: youtube
        href: https://www.youtube.com/@cerema3139      


format:
  html:
    html-math-method: katex
    theme: [flatly, custom.scss]
    include-in-header:
      - text: |
          <script type="text/javascript" src="js/print_all_tab_expand_collapse.js"></script>
    template-partials:
      - _partials/title-block.html
    toc: true
    toc-location: left
    toc-depth: 3

editor: source